version: "3.9"
   
services:
  # FastAPI
  web:
    build: .
    container_name: indago-api
    command: uvicorn api.main:app --host 0.0.0.0 --port 1444 --reload # TODO remove --reload for production use
    restart: always
    volumes:
      - .:/code
      - /data:/data
      #- /media/ponbac/BigHDD/ethereum:/data
    ports:
      - "1444:1444"
    environment:
      - DB_HOST=DOCKER # =AWS for hosted DB (ALSO CHANGE POSTGRES_PASSWORD), =DOCKER for local DB
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - ETHERSCAN_API_KEY=
      - GOOGLE_APPLICATION_CREDENTIALS=/code/google-auth.json